export const auditLabels: Record<string, string> = {
  "owner.bootstrapped": "Pemilik pertama dibuat",
  "operator.created": "Staf dibuat",
  "operator.role_changed": "Peran staf diubah",
  "operator.activated": "Staf diaktifkan",
  "operator.deactivated": "Staf dinonaktifkan",
  "operator.password_reset": "Password staf diganti",
  "product.created": "Produk dibuat",
  "product.updated": "Produk diubah",
  "product.unpublished": "Produk menjadi draft",
  "product.published": "Produk dipublikasikan",
  "product.archived": "Produk diarsipkan",
  "category.updated": "Kategori diubah",
  "media.attached": "Foto ditambahkan",
  "media.updated": "Foto diubah",
  "media.removed": "Foto dihapus",
  "payment.verified": "Pembayaran diverifikasi",
  "payment.rejected": "Pembayaran ditolak",
  "order.status_changed": "Status pesanan diubah",
  "order.process": "Pesanan diproses",
  "order.ship": "Pesanan dikirim",
  "order.complete": "Pesanan selesai",
  "tracking.changed": "Informasi pengiriman diubah",
  "banner.updated": "Banner diubah",
  "banner.deleted": "Banner dihapus",
  "social.updated": "Media sosial diubah",
  "seo.updated": "SEO diubah",
  "store.updated": "Pengaturan toko diubah",
  "bank.updated": "Rekening diubah",
  "bank.deleted": "Rekening dihapus",
  "promotion.updated": "Promosi diubah",
  "product.eligibility_changed": "Kelayakan promosi diubah",
  "review.moderated": "Ulasan dimoderasi",
  "qris.updated": "QRIS diubah",
  "inventory.adjusted": "Jumlah stok disesuaikan",
};
